import { PERMISSION_TYPE } from '@/shared/enum/permission.enum'

export const PERMISSIONS = {
  SESSION_GUARD: 'SESSION_GUARD', // Permiso especial para acceder a páginas protegidas
  
  // Monitor permissions
  CAN_CREATE_MONITOR: PERMISSION_TYPE.CAN_CREATE_MONITOR,
  CAN_EDIT_MONITOR: PERMISSION_TYPE.CAN_EDIT_MONITOR,
  CAN_ENABLE_MONITOR: PERMISSION_TYPE.CAN_ENABLE_MONITOR,
  CAN_DELETE_MONITOR: PERMISSION_TYPE.CAN_DELETE_MONITOR,
  CAN_GENERATE_NEW_URL: PERMISSION_TYPE.CAN_GENERATE_NEW_URL,
  
  // User permissions
  CAN_CREATE_USER: PERMISSION_TYPE.CAN_CREATE_USER,
  CAN_EDIT_USER: PERMISSION_TYPE.CAN_EDIT_USER,
  CAN_ENABLE_USER: PERMISSION_TYPE.CAN_ENABLE_USER,
  CAN_DELETE_USER: PERMISSION_TYPE.CAN_DELETE_USER,
  
  // Role permissions
  CAN_CREATE_ROLE: PERMISSION_TYPE.CAN_CREATE_ROLE,
  CAN_EDIT_ROLE: PERMISSION_TYPE.CAN_EDIT_ROLE,
  CAN_DELETE_ROLE: PERMISSION_TYPE.CAN_DELETE_ROLE,
  
  // Report permissions
  CAN_VIEW_REPORTS: PERMISSION_TYPE.CAN_VIEW_REPORTS,
} as const

export type PermissionKey = keyof typeof PERMISSIONS
export type PermissionValue = typeof PERMISSIONS[PermissionKey]